version: '3.8'

services:
  db:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - caddy

volumes:
  postgres_data:

networks:
  caddy:
    external: true
